# fly.toml app configuration file generated for govuk-mcp on 2026-04-11T03:34:58+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'govuk-mcp'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 50
    soft_limit = 25

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
